v1.5.1: check we are root

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12,6 +12,12 @@
 #
 set -e
 
+# Vérifier qu'on est bien sous root
+if [ "$(id -u)" != "0" ]; then
+  echo >&2 "${COLOR_ERROR}ERREUR :${COLOR_NONE} ce script nécessite les droits root."
+  exit 255
+fi
+
 if [ "$1" = "purge" ] || [ "$1" = "remove" ]; then
   rm "/usr/local/sbin/fix-aptitude-dependencies" 2>/dev/null || true
   if [ "$1" = "purge" ]; then
diff --git a/fix-aptitude-dependencies b/fix-aptitude-dependencies
--- a/fix-aptitude-dependencies
+++ b/fix-aptitude-dependencies
@@ -488,6 +488,12 @@ SCRIPT_NAME_CONF="${COLOR_ARGUMENT}$(basename "$(readlink -f "$0")").conf${COLOR
 APTITUDE_VERSION="$(aptitude_version)"
 aptitude_pending_actions_pattern > /dev/null
 
+# Vérifier qu'on est bien sous root
+if [ "$(id -u)" != "0" ]; then
+  echo >&2 "${COLOR_ERROR}ERREUR :${COLOR_NONE} ce script nécessite les droits root."
+  exit 255
+fi
+
 # Créer le répertoire temporaire / mutex d'instance.
 create_instance_lockdir
 
