v1.1 - Split configuration file => /etc/fix-aptitude-dependencies.conf

diff --git a/fix-aptitude-dependencies b/fix-aptitude-dependencies
--- a/fix-aptitude-dependencies
+++ b/fix-aptitude-dependencies
@@ -15,54 +15,6 @@
 #
 
 
-#-----------------------------------------------------------------------------
-# Variables personnalisables
-#-----------------------------------------------------------------------------
-
-
-#
-# Liste des paquets à forcer en Manuel, séparés par des espaces, tabulations,
-# ou retours chariots.
-#
-# À minima, indiquer ici des paquets possédant des dépendances circulaires
-# (par exemple, tasksel pour le groupe tasksel et tasksel-data) faute de quoi ces
-# paquets seront tous marqués en Manuel et le script grognera à chaque exécution.
-# Pas d'inquiétude à avoir, ce script vous avertira dans tous les cas pour que
-# vous puissiez rajouter les paquets correspondants dans cette liste.
-#
-# Vous pouvez aussi indiquer ici les paquets que vous souhaitez absolument garder
-# en Manuel quoi qu'il arrive (notamment pour éviter que la désinstallation d'un
-# métapaquet n'entraîne la désinstallation automatique d'un paquet important).
-#
-MANUAL_PACKAGES=""
-
-
-#
-# Fonction appellée à la fin du script si tout s'est bien passé, permettant d'ajouter
-# des nettoyages personnalisés (par exemple « aptitude clean »).
-#
-user_defined_cleanup()
-{
-}
-
-
-#
-# Fonction appellée pour déterminer les paquets orphelins.
-# Vous pouvez personnaliser le comportement de « deborphan » comme vous le souhaitez,
-# du moment que la liste retournée ne contient que des noms de paquets (un par ligne).
-# L'option « --no-show-section » est donc très importante.
-#
-user_defined_deborphan()
-{
-  deborphan --ignore-suggests --guess-interpreters --no-show-section
-}
-
-
-#-----------------------------------------------------------------------------
-# NE RIEN MODIFIER À PARTIR D'ICI
-#-----------------------------------------------------------------------------
-
-
 # Emplacement du répertoire temporaire
 LOCK_DIR="/tmp/fix-aptitude-auto.lock"
 # Couleurs
@@ -76,6 +28,18 @@ shopt -s xpg_echo
 # Forcer la sortie des commandes en anglais pour faciliter le scripting.
 export LANG=""
 export LANGUAGE=""
+
+
+#-----------------------------------------------------------------------------
+# Importer la configuration
+#-----------------------------------------------------------------------------
+CONFIG_FILE="/etc/fix-aptitude-dependencies.conf"
+
+if [ -f "$CONFIG_FILE" ]; then
+  . "$CONFIG_FILE" || echo >&2 "${COLOR_ERROR}ERREUR :${COLOR_NONE} problème lors de la lecture du fichier de configuration « ${COLOR_ARGUMENT}$CONFIG_FILE${COLOR_NONE} »."
+else
+  echo >&2 "${COLOR_ERROR}ERREUR :${COLOR_NONE} le fichier de configuration « ${COLOR_ARGUMENT}$CONFIG_FILE${COLOR_NONE} » n'existe pas."
+fi
 
 
 #-----------------------------------------------------------------------------
